http:
  host: 'localhost'
  port: ':8080'
grpc:
  host: 'localhost'
  port: ':50051'
postgres:
  max_connections: 50
nuts:
  cluster_id: 'test-cluster'
  client_sub_id: 'subscriber'
  client_pub_id: 'publisher'
  subject: 'order'
  url: 'nats://nats-streaming:4222'