http:
  host: 'localhost'
  port: ':8084'
grpc:
  host: 'localhost'
  port: ':50051'
postgres:
  max_connections: 1
nuts:
  cluster_id: 'test-cluster'
  client_sub_id: 'subscriber'
  client_pub_id: 'publisher'
  subject: 'order'
  url: 'nats://nats-streaming:4222' #docker
  #url: 'nats://localhost:4222' #localtest
cache:
  default_expiration: 0m
  cleanup_interval: 0m